// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Skaldling.Api.Infrastructure.Persistence;

#nullable disable

namespace Skaldling.Api.Migrations
{
    [DbContext(typeof(SkaldlingDbContext))]
    [Migration("20260522004705_AddAvatarConfigToHero")]
    partial class AddAvatarConfigToHero
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Skaldling.Api.Domain.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AchievementPoints")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("Skaldling.Api.Domain.Sprite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchetypeFamily")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AssetPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("Layer")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Dictionary<string, object>>("Tags")
                        .HasColumnType("jsonb");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sprites");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0000-000000000001"),
                            ArchetypeFamily = "Human",
                            AssetPath = "/sprites/body/human-base.svg",
                            Description = "A slender human figure standing at ease, neutral posture.",
                            IsDefault = true,
                            Layer = 10,
                            Name = "human-base",
                            Type = "BodyArchetype"
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0002-0000-000000000001"),
                            ArchetypeFamily = "Beast",
                            AssetPath = "/sprites/body/beast-base.svg",
                            Description = "A sturdy creaturely figure with broad shoulders and a slight crouch, standing on its hind legs.",
                            IsDefault = true,
                            Layer = 10,
                            Name = "beast-base",
                            Type = "BodyArchetype"
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0003-0000-000000000001"),
                            ArchetypeFamily = "Robot",
                            AssetPath = "/sprites/body/robot-base.svg",
                            Description = "An angular humanoid robot frame in muted brushed steel, standing upright.",
                            IsDefault = true,
                            Layer = 10,
                            Name = "robot-base",
                            Type = "BodyArchetype"
                        },
                        new
                        {
                            Id = new Guid("11111111-0006-0000-0000-000000000001"),
                            ArchetypeFamily = "Human",
                            AssetPath = "/sprites/outfit-bottom/brown-trousers.svg",
                            Description = "Practical brown trousers tucked into short boots.",
                            IsDefault = true,
                            Layer = 20,
                            Name = "brown-trousers",
                            Type = "OutfitBottom"
                        },
                        new
                        {
                            Id = new Guid("11111111-0005-0000-0000-000000000001"),
                            ArchetypeFamily = "Human",
                            AssetPath = "/sprites/outfit-top/leather-vest.svg",
                            Description = "A worn leather vest with brass buttons over a coarse linen shirt.",
                            IsDefault = true,
                            Layer = 30,
                            Name = "leather-vest",
                            Type = "OutfitTop"
                        },
                        new
                        {
                            Id = new Guid("11111111-0005-0000-0000-000000000002"),
                            ArchetypeFamily = "Human",
                            AssetPath = "/sprites/outfit-top/woolen-tunic.svg",
                            Description = "A heavy moss-green woolen tunic, cinched at the waist.",
                            IsDefault = true,
                            Layer = 30,
                            Name = "woolen-tunic",
                            Type = "OutfitTop"
                        },
                        new
                        {
                            Id = new Guid("11111111-0002-0001-0000-000000000001"),
                            ArchetypeFamily = "Human",
                            AssetPath = "/sprites/face/human-face.svg",
                            Description = "A calm, attentive human face with a small mouth and a steady gaze.",
                            IsDefault = true,
                            Layer = 40,
                            Name = "human-face",
                            Type = "Face"
                        },
                        new
                        {
                            Id = new Guid("11111111-0002-0002-0000-000000000001"),
                            ArchetypeFamily = "Beast",
                            AssetPath = "/sprites/face/beast-face.svg",
                            Description = "An expressive creature face with a warm-toned snout and watchful eyes.",
                            IsDefault = true,
                            Layer = 40,
                            Name = "beast-face",
                            Type = "Face"
                        },
                        new
                        {
                            Id = new Guid("11111111-0002-0003-0000-000000000001"),
                            ArchetypeFamily = "Robot",
                            AssetPath = "/sprites/face/robot-face.svg",
                            Description = "A smooth metallic faceplate with sensor eyes and a thin speaker grille.",
                            IsDefault = true,
                            Layer = 40,
                            Name = "robot-face",
                            Type = "Face"
                        },
                        new
                        {
                            Id = new Guid("11111111-0003-0000-0000-000000000001"),
                            ArchetypeFamily = "Human",
                            AssetPath = "/sprites/eyes/green-eyes.svg",
                            Description = "Sharp green eyes that catch the light.",
                            IsDefault = true,
                            Layer = 50,
                            Name = "green-eyes",
                            Type = "Eyes"
                        },
                        new
                        {
                            Id = new Guid("11111111-0003-0000-0000-000000000002"),
                            ArchetypeFamily = "Human",
                            AssetPath = "/sprites/eyes/brown-eyes.svg",
                            Description = "Warm brown eyes, gentle and curious.",
                            IsDefault = true,
                            Layer = 50,
                            Name = "brown-eyes",
                            Type = "Eyes"
                        },
                        new
                        {
                            Id = new Guid("11111111-0004-0000-0000-000000000001"),
                            ArchetypeFamily = "Human",
                            AssetPath = "/sprites/hair/curly-red-hair.svg",
                            Description = "Long curly rust-red hair tied with a thin leather thong, falling past the shoulders.",
                            IsDefault = true,
                            Layer = 60,
                            Name = "curly-red-hair",
                            Type = "Hair"
                        },
                        new
                        {
                            Id = new Guid("11111111-0004-0000-0000-000000000002"),
                            ArchetypeFamily = "Human",
                            AssetPath = "/sprites/hair/short-black-hair.svg",
                            Description = "Short jet-black hair, slightly tousled.",
                            IsDefault = true,
                            Layer = 60,
                            Name = "short-black-hair",
                            Type = "Hair"
                        },
                        new
                        {
                            Id = new Guid("11111111-0004-0000-0000-000000000003"),
                            ArchetypeFamily = "Human",
                            AssetPath = "/sprites/hair/long-blonde-hair.svg",
                            Description = "Long flowing honey-blonde hair that reaches the upper back.",
                            IsDefault = true,
                            Layer = 60,
                            Name = "long-blonde-hair",
                            Type = "Hair"
                        },
                        new
                        {
                            Id = new Guid("11111111-0007-0000-0000-000000000001"),
                            ArchetypeFamily = "Human",
                            AssetPath = "/sprites/accessory/feathered-cap.svg",
                            Description = "A dusty-blue cap with a single eagle feather angling skyward.",
                            IsDefault = true,
                            Layer = 70,
                            Name = "feathered-cap",
                            Type = "Accessory"
                        });
                });

            modelBuilder.Entity("Skaldling.Api.Domain.Hero", b =>
                {
                    b.OwnsOne("Skaldling.Api.Domain.AvatarConfig", "AvatarConfig", b1 =>
                        {
                            b1.Property<Guid>("HeroId");

                            b1.PrimitiveCollection<string>("SpriteIds")
                                .IsRequired();

                            b1.HasKey("HeroId");

                            b1.ToTable("Heroes");

                            b1
                                .ToJson("AvatarConfig")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("HeroId");
                        });

                    b.Navigation("AvatarConfig")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
